import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import favicon from './assets/favicon.svg';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Edu-Insight",
  description: "Generated by create next app",
  icons: [{ rel: 'icon', url: favicon.src }]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
